##########################################################################
### REQUIRED
##########################################################################
variable "action" {
  description = "The AWS Lambda action you want to allow in this statement"
  type        = string
}

variable "function_name" {
  description = "Name of the Lambda function whose resource policy you are updating"
  type        = string
}

variable "principal" {
  description = "The principal who is getting this permission e.g., `s3.amazonaws.com`, an AWS account ID, or any valid AWS service principal such as `events.amazonaws.com` or `sns.amazonaws.com`"
  type        = string
}

##########################################################################
### OPTIONAL
##########################################################################
variable "event_source_token" {
  default     = null
  description = "The Event Source Token to validate"
  type        = string
}

variable "function_url_auth_type" {
  default     = null
  description = "Lambda Function URLs authentication type. Valid values are: `AWS_IAM` or `NONE`"
  type        = string
}

variable "qualifier" {
  default     = null
  description = "Query parameter to specify function version or alias name. The permission will then apply to the specific qualified ARN e.g., `arn:aws:lambda:aws-region:acct-id:function:function-name:2`"
  type        = string
}

variable "source_account" {
  default     = null
  description = "This parameter is used for S3 and SES. The AWS account ID (without a hyphen) of the source owner"
  type        = string
}

variable "source_arn" {
  default     = null
  description = " When the principal is an AWS service, the ARN of the specific resource within that service to grant permission to"
  type        = string
}

variable "statement_id" {
  default     = null
  description = "A unique statement identifier. By default generated by Terraform"
  type        = string
}

variable "statement_id_prefix" {
  default     = null
  description = "A statement identifier prefix. Terraform will generate a unique suffix. Conflicts with `statement_id`"
  type        = string
}

variable "principal_org_id" {
  default     = null
  description = "The identifier for your organization in AWS Organizations. Use this to grant permissions to all the AWS accounts under this organization"
  type        = string
}
